from django.urls import path
from . import node_compat
from . import views

urlpatterns = [
    path('', views.inicio),
    path('persona/', views.persona_page),
    path('propietario/', views.propietario_page),
    path('recoleccion/', views.recoleccion_page),
    path('recolector/', views.recolector_page),
    path('reporte/', views.reporte_page),
    path('finca/', views.finca_page),
    path('insumo/', views.insumo_page),
    path('pago/', views.pago_page),
    path('mantenimiento/', views.mantenimiento_page),
    path('tipo_doc/', views.tipo_doc_page),
    path('tipo_insumo/', views.tipo_insumo_page),
    path('unidad_medida/', views.unidad_medida_page),
    path('metodo_aplicacion/', views.metodo_aplicacion_page),
    path('vista_admin/', views.vista_admin),
    path('vista_propietario/', views.vista_propietario),
    path('vista_recolector/', views.vista_recolector),
    path('perfil_recolector/', views.perfil_recolector),
    path('lote/', views.lote_page),
    path('compra/', views.compra_page),
    path('inventario/', views.inventario_page),
    path('suministro/', views.suministro_page),
    path('insert_persona/', views.insert_persona, name='insert_persona'),
    path('insert_persona_temporal/', views.insert_persona_temporal, name='insert_persona_temporal'),
    path('obtener_persona_temporal/', views.obtener_persona_temporal, name='obtener_persona_temporal'),
    path('insert_propietario/', views.insert_propietario, name='insert_propietario'),
    path('insert_recolector/', views.insert_recolector, name='insert_recolector'),
    path('insert_reporte/', views.insert_reporte, name='insert_reporte'),
    path('insert_recoleccion/', views.insert_recoleccion, name='insert_recoleccion'),
    path('insert_finca/', views.insert_finca, name='insert_finca'),
    path('insert_lote/', views.insert_lote, name='insert_lote'),
    path('insert_insumo/', views.insert_insumo, name='insert_insumo'),
    path('insert_pago/', views.insert_pago, name='insert_pago'),
    path('insert_mantenimiento/', views.insert_mantenimiento, name='insert_mantenimiento'),
    path('insert_tipodocumento/', views.insert_tipodocumento, name='insert_tipodocumento'),
    path('insert_compra/', views.insert_compra, name='insert_compra'),
    path('insert_evento_recoleccion/', views.insert_evento_recoleccion, name='insert_evento_recoleccion'),
    path('insert_inventario/', views.insert_inventario, name='insert_inventario'),
    path('insert_suministro/', views.insert_suministro, name='insert_suministro'),
    path('consultar_registro/<str:nombre_tabla>/<str:id_registro>/', views.consultar_registro, name='consultar_registro'),
    path('corregir_registro/<str:nombre_tabla>/<str:id_registro>/', views.corregir_registro, name='corregir_registro'),
    path('eliminar_registro/<str:nombre_tabla>/<str:id_registro>/', views.eliminar_registro, name='eliminar_registro'),
    path('get_todos/<str:nombre_tabla>/', views.get_todos, name='get_todos'),
]

# Rutas tipo API Node (localhost:3000) → proxy FastAPI / Postgres / RDF
urlpatterns += [
    path('api/productosfinca', node_compat.api_productosfinca),
    path('api/productosfinca/<str:id_finca>', node_compat.api_productosfinca_id),
    path('api/productoslote', node_compat.api_productoslote),
    path('api/productoslote/<str:id_lote>', node_compat.api_productoslote_id),
    path('api/recoleccion', node_compat.api_recoleccion),
    path('api/recoleccion/<str:id_recoleccion>', node_compat.api_recoleccion_id),
    path('api/productosreporte', node_compat.api_productosreporte),
    path('api/productosreporte/<str:id_reporte>', node_compat.api_productosreporte_id),
    path('api/pago', node_compat.api_pago),
    path('api/pago/<str:id_pago>', node_compat.api_pago_id),
    path('api/insumos', node_compat.api_insumos),
    path('api/insumos/<str:id_insumo>', node_compat.api_insumos_id),
    path('api/productostipocafe', node_compat.api_productostipocafe),
    path('api/productostipocafe/<str:id_tipocafe>', node_compat.api_productostipocafe_id),
    path('api/productosTipodoc', node_compat.api_productos_tipodoc),
    path('api/productosTipodoc/<str:id_tipodoc>', node_compat.api_productos_tipodoc_id),
    path('api/connectMongo', node_compat.api_connect_mongo),
    path('api/recoleccionesvista/<str:documento_persona>', node_compat.api_recolecciones_vista),
    path('api/tiposinsumo', node_compat.api_tiposinsumo),
    path('api/tiposinsumo/<str:id_tipoinsumo>', node_compat.api_tiposinsumo_id),
    path('api/productostiposinsumo/<str:id_tipoinsumo>', node_compat.api_productostiposinsumo_id),
    path('api/productosmedida', node_compat.api_productosmedida),
    path('api/productosmedida/<str:id_unidadmedida>', node_compat.api_productosmedida_id),
    path('api/productosmetodoaplica', node_compat.api_productosmetodoaplica),
    path('api/productosmetodoaplica/<str:id_metodoaplicacion>', node_compat.api_productosmetodoaplica_id),
    path('api/reporte_diario', node_compat.api_reporte_diario),
    path('api/liquidacion_recolector', node_compat.api_liquidacion_recolector),
    path('api/finanzas_kg_sugerido', node_compat.api_finanzas_kg_sugerido),
    path('api/finanzas_generar_pago', node_compat.api_finanzas_generar_pago),
]
